// POSTS
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST'
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS'
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE' 

export const DELETE_POST = 'DELETE_POST'
export const EDIT_POST = 'EDIT_POST'

export const UP_VOTE_POST_REQUEST = 'UP_VOTE_POST_REQUEST'
export const UP_VOTE_POST_SUCCESS = 'UP_VOTE_POST_SUCCESS'
export const UP_VOTE_POST_FAILURE = 'UP_VOTE_POST_FAILURE'

export const DOWN_VOTE_POST_REQUEST = 'DOWN_VOTE_POST_REQUEST'
export const DOWN_VOTE_POST_SUCCESS = 'DOWN_VOTE_POST_SUCCESS'
export const DOWN_VOTE_POST_FAILURE = 'DOWN_VOTE_POST_FAILURE'

// CATEGORIES
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'

// FILTER
// export const SET_FILTER = 'SET_FILTER'
// export const CLEAR_FILTER = 'CLEAR_FILTER'

// COMMENTS
export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE'

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_FAILURE = 'CREATE_COMMENT_FAILURE' 

export const DELETE_COMMENT = 'DELETE_COMMENT'
export const EDIT_COMMENT = 'EDIT_COMMENT'
