// POSTS
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

// CATEGORIES
export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'

// FILTER
export const SET_FILTER = 'SET_FILTER'
export const CLEAR_FILTER = 'CLEAR_FILTER'

// COMMENTS
// export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST'
// export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS'
// export const FETCH_COMMENTS_FAILURE = 'FETCH_COMMENTS_FAILURE'
