// posts
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const CREATE_POSTS_REQUEST = 'CREATE_POSTS_REQUEST'
export const CREATE_POSTS_SUCCESS = 'CREATE_POSTS_SUCCESS'
export const CREATE_POSTS_FAILURE = 'CREATE_POST_FAILURE'

export const EDIT_POST = 'EDIT_POST'
export const DELETE_POST = 'DELETE_POST'